### ISSUE TITLE
Update Packages to download

### ISSUE THREAD

**Issue by DoctorFuchs** [HGLabor/HGLaborUtils#5]
Hey can you please update the packages to download, so you can download the .jar file.
Thank you

**Comment by mooziii** [comment]
hey, you can download the newsest jarfile [here](https://repo1.maven.org/maven2/de/hglabor/hglabor-utils/0.0.11/hglabor-utils-0.0.11.jar)

**Comment by DoctorFuchs** [comment]
thx
